before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf0 
script: bundle exec rake spec
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ruby-head
  - rbx-1.3.3
  - rbx-2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
cache: bundler
